// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bookingdesks.Data;

#nullable disable

namespace API_bookingdesks.Data.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("bookingdesks.Data.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfDesks")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoomId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomId = 1,
                            Adress = "Room 1",
                            NumberOfDesks = 7
                        },
                        new
                        {
                            RoomId = 2,
                            Adress = "Room 2",
                            NumberOfDesks = 7
                        },
                        new
                        {
                            RoomId = 3,
                            Adress = "Room 3",
                            NumberOfDesks = 7
                        },
                        new
                        {
                            RoomId = 4,
                            Adress = "Room 4",
                            NumberOfDesks = 7
                        },
                        new
                        {
                            RoomId = 5,
                            Adress = "Room 5",
                            NumberOfDesks = 7
                        },
                        new
                        {
                            RoomId = 6,
                            Adress = "Room 6",
                            NumberOfDesks = 7
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
